import java.util.ArrayList;
import javax.swing.JOptionPane;


public class Inicio_sesion extends javax.swing.JFrame {

    private int contcontras=0,contusuarios=0;    
    private String contra; 
    private String usuario;
    static ArrayList<Usuarios> ListadeUsuarios;
    public Inicio_sesion(ArrayList<Usuarios> AtributListadeUsuarios) {
        if(AtributListadeUsuarios==null){
        ListadeUsuarios = new ArrayList<Usuarios>();
        System.out.println("se crea nuevo");
        }else{
        System.out.println("acepta atributo");
        ListadeUsuarios=AtributListadeUsuarios; 
            
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        Username = new javax.swing.JTextField();
        Crear_Player = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Ussename = new javax.swing.JLabel();
        Pasword = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 120, 30));

        Crear_Player.setBackground(new java.awt.Color(51, 51, 51));
        Crear_Player.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Crear_Player.setForeground(new java.awt.Color(255, 255, 255));
        Crear_Player.setText("Crear Player");
        Crear_Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_PlayerActionPerformed(evt);
            }
        });
        getContentPane().add(Crear_Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 120, 30));

        Ussename.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Ussename.setForeground(new java.awt.Color(255, 255, 255));
        Ussename.setText("Username");
        getContentPane().add(Ussename, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 120, 20));

        Pasword.setBackground(new java.awt.Color(51, 51, 51));
        Pasword.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Pasword.setForeground(new java.awt.Color(255, 255, 255));
        Pasword.setText("Password");
        getContentPane().add(Pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        Back.setBackground(new java.awt.Color(51, 51, 51));
        Back.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Regresar");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 90, -1));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_PlayerActionPerformed
        // TODO add your handling code here:
        Crear_Player Cp=new Crear_Player(ListadeUsuarios);
        Cp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Crear_PlayerActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
         if(this.contusuarios==0){
       Username.setText("");
       contusuarios=1;
       
       }    
    }//GEN-LAST:event_UsernameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        if(contcontras==0){
         Password.setText("");
         contcontras=1;    
        }
    }//GEN-LAST:event_PasswordActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
            Main fn = new Main(ListadeUsuarios);
            fn.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
         int posicion = -1;

    for (int i = 0; i < ListadeUsuarios.size(); i++) {
        if (ListadeUsuarios.get(i).Nombre.equals(Username.getText())) {
            usuario = Username.getText();
            posicion = i;
            break;
        }
    }

    if (posicion != -1) {
        if (ListadeUsuarios.get(posicion).getcontra().equals(Password.getText())) {
            JOptionPane.showMessageDialog(null, "Inicio de sesión correcto");
            contra = Password.getText();
            
            // Open the menu_principal1 JFrame
            menu_principal menusito = new menu_principal (ListadeUsuarios, Username.getText(), Password.getText(), this);
            menusito.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Usuario no existe");
    }
        
    }//GEN-LAST:event_AceptarActionPerformed
    private String infoUsuario(String usuario){
    this.usuario=usuario;
    return usuario;
    }
    private String infoContra(String contra){
        this.contra=contra;
        return contra;
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Back;
    private javax.swing.JButton Crear_Player;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Pasword;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel Ussename;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
