
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class menu_principal extends javax.swing.JFrame {

    static ArrayList<Usuarios> ListadeUsuarios;
        String nombreUsuario;
        String contraUsuario;
        private Inicio_sesion loginWindow;
    public menu_principal(ArrayList<Usuarios> AtributListadeUsuarios,String nombreUsuario,String contraUsuario,Inicio_sesion loginWindow){
        this.nombreUsuario = nombreUsuario;
        this.contraUsuario=contraUsuario;
        this.loginWindow = loginWindow;
        ListadeUsuarios = AtributListadeUsuarios;
        initComponents();
        System.out.println("Nombre usuario: "+nombreUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configuracion = new javax.swing.JToggleButton();
        reportes = new javax.swing.JToggleButton();
        perfil = new javax.swing.JToggleButton();
        salir = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        Jugar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        configuracion.setText("Configuracion");
        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });
        getContentPane().add(configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        reportes.setText("Reportes");
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        getContentPane().add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));

        perfil.setText("Mi Perfil");
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jugar.setText("Jugar");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        jPanel1.add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, -1));

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
         int opcion=JOptionPane.showConfirmDialog(null, "Desea salir?", " Salir", JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
        // TODO add your handling code here:
        configuracion op= new configuracion(ListadeUsuarios,nombreUsuario,contraUsuario,loginWindow);
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_configuracionActionPerformed
   // TODO add your handling code here:
    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        // TODO add your handling code here:
        Reportes fp= new Reportes(ListadeUsuarios,nombreUsuario,contraUsuario,loginWindow);
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportesActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        // TODO add your handling code here:
       Perfil profile=new Perfil(this.ListadeUsuarios,nombreUsuario,contraUsuario, loginWindow);
       profile.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_perfilActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
    Validacionname fk =new Validacionname(ListadeUsuarios,nombreUsuario,contraUsuario);
    fk.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_JugarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Inicio_sesion menuWindow = new Inicio_sesion(ListadeUsuarios);
    menuWindow.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jugar;
    private javax.swing.JToggleButton configuracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton perfil;
    private javax.swing.JToggleButton reportes;
    private javax.swing.JToggleButton salir;
    // End of variables declaration//GEN-END:variables
}
