
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 *
 * while(entrar)
 *
 * @author Kenny
 *
 *
 *
 *
 *
 *
 */
public class tableromain extends javax.swing.JFrame {
    //para ver si la persona coloco los barcos y mostrar mensaje 

    /**
     * Creates new form tableromain
     */
    String Usuario;
     String contra;
     private Inicio_sesion loginWindow;
    static ArrayList<Usuarios> ListadeUsuarios;
    private boolean turno1 = true;
    private boolean turno2 = false;
    private boolean triago = false;
    private boolean colocados1;
    private boolean colocados2;
    private boolean winner;
    segundo_tablero hola;
    Izquierdo_Tablero op;
    public tableromain(ArrayList<Usuarios> AtributListadeUsuarios,String nombreUsuario,String contraUsuario,Inicio_sesion loginWindow) {
       
        this.Usuario = nombreUsuario;
        this.contra=contraUsuario;
        this.loginWindow = loginWindow;
        this.ListadeUsuarios = AtributListadeUsuarios;
        //primer tablero
        initComponents();
        hola = new segundo_tablero(AtributListadeUsuarios);
        op = new Izquierdo_Tablero(AtributListadeUsuarios);
        op.setSize(300, 300);
        op.setLocation(0, 0);
        primertableropanel.add(op, BorderLayout.CENTER);
        primertableropanel.revalidate();
        primertableropanel.repaint();
        //segundo tablero 
        hola.setSize(300, 300);
        hola.setLocation(0, 0);
        secon_tablero.removeAll();
        secon_tablero.add(hola, BorderLayout.CENTER);
        secon_tablero.revalidate();
        secon_tablero.repaint();
        String player1 =Almacen_datos.getPlayer1();
        String player2 =Almacen_datos.getPlayer2();
        Player1.setText(player1);
        Player2.setText(player2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primertableropanel = new javax.swing.JPanel();
        acorazadobutton = new javax.swing.JButton();
        portaaviones = new javax.swing.JButton();
        submarinobutton = new javax.swing.JButton();
        Destructorbutton = new javax.swing.JButton();
        verticalbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        horizontolbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        secon_tablero = new javax.swing.JPanel();
        verticalbutton1 = new javax.swing.JButton();
        horizontalbotton1 = new javax.swing.JButton();
        portaaviones2se = new javax.swing.JButton();
        submarinobotton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        destructorbutton2 = new javax.swing.JButton();
        acorazadobutton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rendir1 = new javax.swing.JButton();
        Rendirse2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Player1 = new java.awt.Label();
        Player2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primertableropanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout primertableropanelLayout = new javax.swing.GroupLayout(primertableropanel);
        primertableropanel.setLayout(primertableropanelLayout);
        primertableropanelLayout.setHorizontalGroup(
            primertableropanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        primertableropanelLayout.setVerticalGroup(
            primertableropanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(primertableropanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 300, 300));
        primertableropanel.getAccessibleContext().setAccessibleName("");

        acorazadobutton.setText("Acorazado");
        acorazadobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acorazadobuttonActionPerformed(evt);
            }
        });
        getContentPane().add(acorazadobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        portaaviones.setText("Portaaviones");
        portaaviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaavionesActionPerformed(evt);
            }
        });
        getContentPane().add(portaaviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, -1));

        submarinobutton.setText("Submarino");
        submarinobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submarinobuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submarinobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, -1));

        Destructorbutton.setText("Destructor");
        Destructorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestructorbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Destructorbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, -1));

        verticalbutton.setText("Vertical");
        verticalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(verticalbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        jLabel5.setText("Selecione el lado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));

        horizontolbutton.setText("Horizontal");
        horizontolbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horizontolbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(horizontolbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));

        jLabel6.setText("Elija el tipo de barco:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 20));

        jLabel1.setText("Selecione el lado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 110, 20));

        secon_tablero.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout secon_tableroLayout = new javax.swing.GroupLayout(secon_tablero);
        secon_tablero.setLayout(secon_tableroLayout);
        secon_tableroLayout.setHorizontalGroup(
            secon_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        secon_tableroLayout.setVerticalGroup(
            secon_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(secon_tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 300, 300));

        verticalbutton1.setText("Vertical");
        verticalbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(verticalbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 90, -1));

        horizontalbotton1.setText("Horizontal");
        horizontalbotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horizontalbotton1ActionPerformed(evt);
            }
        });
        getContentPane().add(horizontalbotton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 90, -1));

        portaaviones2se.setText("Portaaviones");
        portaaviones2se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaaviones2seActionPerformed(evt);
            }
        });
        getContentPane().add(portaaviones2se, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 110, -1));

        submarinobotton2.setText("Submarino");
        submarinobotton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submarinobotton2ActionPerformed(evt);
            }
        });
        getContentPane().add(submarinobotton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 110, -1));

        jLabel2.setText("Elija el tipo de barco:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 130, 20));

        destructorbutton2.setText("Destructor");
        destructorbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destructorbutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(destructorbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 110, -1));

        acorazadobutton2.setText("Acorazado");
        acorazadobutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acorazadobutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(acorazadobutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 110, -1));

        jLabel3.setText("Player: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        jLabel4.setText("Player:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 50, -1));

        Rendir1.setText("Rendirse");
        Rendir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rendir1ActionPerformed(evt);
            }
        });
        getContentPane().add(Rendir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        Rendirse2.setText("Rendirse");
        Rendirse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rendirse2ActionPerformed(evt);
            }
        });
        getContentPane().add(Rendirse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, -1, 20));

        jLabel7.setText("(Player1)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel8.setText("(Player2)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, -1, -1));

        Player1.setForeground(new java.awt.Color(0, 0, 0));
        Player1.setText("label1");
        getContentPane().add(Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        Player2.setForeground(new java.awt.Color(0, 0, 0));
        Player2.setText("label2");
        getContentPane().add(Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acorazadobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acorazadobuttonActionPerformed
        // TODO add your handling code here:
        colocados1 = Almacen_datos.isColocado1();
        if (!colocados1) {
            op.setacorazado(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_acorazadobuttonActionPerformed

    private void portaavionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaavionesActionPerformed
        colocados1 = Almacen_datos.isColocado1();
        if (!colocados1) {
            op.setporta(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_portaavionesActionPerformed

    private void submarinobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submarinobuttonActionPerformed
        // TODO add your handling code here:
        colocados1 = Almacen_datos.isColocado1();
        if (!colocados1) {
            op.setsubamarino(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submarinobuttonActionPerformed

    private void DestructorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestructorbuttonActionPerformed
        // TODO add your handling code here:
        colocados1 = Almacen_datos.isColocado1();
        if (!colocados1) {
            op.setdestru(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DestructorbuttonActionPerformed

    private void portaaviones2seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaaviones2seActionPerformed
        colocados2 = Almacen_datos.isColocado2();
        if (!colocados2) {
            hola.setporta(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_portaaviones2seActionPerformed

    private void submarinobotton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submarinobotton2ActionPerformed
        colocados2 = Almacen_datos.isColocado2();
        if (!colocados2) {
            hola.setsubamarino(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submarinobotton2ActionPerformed

    private void destructorbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destructorbutton2ActionPerformed
        colocados2 = Almacen_datos.isColocado2();
        if (!colocados2) {
            hola.setdestru(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_destructorbutton2ActionPerformed

    private void acorazadobutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acorazadobutton2ActionPerformed
        colocados2 = Almacen_datos.isColocado2();
        if (!colocados2) {
            hola.setacorazado(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya a colocados todos los barcos\n", "Noticia!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_acorazadobutton2ActionPerformed
    //lado del barco

    private void verticalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalbuttonActionPerformed
        // TODO add your handling code here:
        op.setVertical(true);
    }//GEN-LAST:event_verticalbuttonActionPerformed

    private void horizontolbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horizontolbuttonActionPerformed
        // TODO add your handling code here:
        op.setVertical(false);
    }//GEN-LAST:event_horizontolbuttonActionPerformed


    private void verticalbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalbutton1ActionPerformed
        // TODO add your handling code here:
        hola.setvertical(true);
    }//GEN-LAST:event_verticalbutton1ActionPerformed

    private void horizontalbotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horizontalbotton1ActionPerformed
        // TODO add your handling code here:
        hola.setvertical(false);
    }//GEN-LAST:event_horizontalbotton1ActionPerformed

    private void Rendir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rendir1ActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "  Seguro que desea rendirse?", " Rendirse", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            Almacen_datos.setRetirada1(true);
            this.dispose();
            menu_principal back = new menu_principal(null,null,null,null);
            back.setVisible(true);
        }
    }//GEN-LAST:event_Rendir1ActionPerformed

    private void Rendirse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rendirse2ActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "  Seguro que desea rendirse?", " Rendirse", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            Almacen_datos.setRetirada2(true);
            this.dispose();
            menu_principal back = new menu_principal(null,null,null,null);
            back.setVisible(true);
        }
    }//GEN-LAST:event_Rendirse2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(tableromain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(tableromain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(tableromain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(tableromain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new tableromain(null,null,null,null).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Destructorbutton;
    private java.awt.Label Player1;
    private java.awt.Label Player2;
    private javax.swing.JButton Rendir1;
    private javax.swing.JButton Rendirse2;
    private javax.swing.JButton acorazadobutton;
    private javax.swing.JButton acorazadobutton2;
    private javax.swing.JButton destructorbutton2;
    private javax.swing.JButton horizontalbotton1;
    private javax.swing.JButton horizontolbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton portaaviones;
    private javax.swing.JButton portaaviones2se;
    private javax.swing.JPanel primertableropanel;
    private javax.swing.JPanel secon_tablero;
    private javax.swing.JButton submarinobotton2;
    private javax.swing.JButton submarinobutton;
    private javax.swing.JButton verticalbutton;
    private javax.swing.JButton verticalbutton1;
    // End of variables declaration//GEN-END:variables
}
